cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL,                          
                            document_root=settings.MEDIA_ROOT)

users/urls.py
"""Authenitcation URLs
"""

from django.conf.urls import url, include
from . import views
from . import views as core_views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup_view, name='signup'),
    url(r'^details/$', views.detail_view, name='details'),
    url(r'^myorders/$', views.myorders, name='myorders'),
    url(r'^password/$', views.change_password, name='change_password'),

]

users/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime


class Profile(models.Model):
    FAVORITE_GENRE_CHOICES = (
        ('comedy', 'Comedy'),
        ('horror', 'Horror'),
        ('all', 'All'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=30)
    postcode = models.CharField(max_length=30)
    date_birth = models.DateField(default=datetime.date.today, blank=True)
    # preferred_genre = models.TextField(blank=False)
    preferred_genre = models.CharField(
        max_length=30,
        choices=FAVORITE_GENRE_CHOICES,
    )


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

users/forms.py
# adpated from https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
from django.contrib.auth import login, authenticate
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField



class DateInput(forms.DateInput):
    input_type = 'date'

class ChoiceInput(forms.ChoiceField):
    input_type = 'choice'

class SignUpForm(UserCreationForm):

    address = forms.CharField(max_length=250)
    city = forms.CharField(max_length=30)
    postcode = forms.CharField(max_length=30, help_text='postcode field')
    #date_birth = forms.DateField()
    # preferred_genre = forms.ChoiceField(choices=FAVORITE_GENRE_CHOICES, widget=forms.RadioSelect)

    date_birth=forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'address',
                  'city', 'postcode', )
        widgets = {
            'date_birth': DateInput(),
            # 'preferred_genre': ChoiceInput()

        }

users/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import SignUpForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from orders.models import OrderItem, Order
from shop.models import Product



def signup_view(request):
    """The view that handles sign ups

    Arguments:
        request {request} -- The request

    Returns:
        render -- The sign up form or a redirect to the index
    """

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.address = form.cleaned_data.get('address')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.postcode = form.cleaned_data.get('postcode')
            user.profile.date_birth = form.cleaned_data.get('date_birth')
            # user.profile.preferred_genre = form.cleaned_data.get('preferred_genre')
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'users/signup.html', {'form': form})


def login_view(request):
    """The view that handles logins

    Arguments:
        request {request} -- The request

    Returns:
        render -- The login form or the index is the attempt is successfull
    """
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))

            return redirect('/')
        else:
            messages.error(request, 'Username or Password not correct')
            return redirect('users:login')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    """The view that handles logouts

    Arguments:
        request {request} -- The request

    Returns:
        render -- The logged out page
    """
    if request.method == 'POST':
        logout(request)
        return render(request, 'users/logout.html')

def myorders(request):
    user_order = Order.objects.all()
    item_order = OrderItem.objects.all()
    product= Product.objects.all()
    return render(request, 'users/myorders.html', {'item_order': item_order, 'user_order':user_order , 'product': product})
    
def detail_view(request):

    return render(request, 'users/user_details.html')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return render(request, 'users/password_changed.html')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/password_change.html', {
        'form': form
    })

users/templates/users/login.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
  The Shoppee | Login
{% endblock %}

{% block content %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-15 p-b-20">
            <form class="login100-form validate-form" method="POST">
                {% csrf_token %}
                <span class="login100-form-title p-b-45">
                    Login
                </span>
                <span class="login100-form-avatar">
                    <img src="{% static "images/avatar-01.jpg" %}" alt="AVATAR">
                </span>

                <div class="wrap-input100 validate-input m-t-35 m-b-35" data-validate = "Enter username">
                    
                    {% render_field form.username class="input100" %}
                    <span class="focus-input100" data-placeholder="Username"></span>
                </div>

                <div class="wrap-input100 validate-input m-b-50" data-validate="Enter password">
                    
                    {% render_field form.password class="input100" type="password" name="pass" %}
                    <span class="focus-input100" data-placeholder="Password"></span>
                </div>
                {% for message in messages %}
                <span class="txt2 login-more p-t-1 ">
                    {{ message }}
                    
                </span>
                {% endfor %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        Login
                    </button>
                </div>

            </form>
                <ul class="login-more p-t-30">
                    <li class="m-b-8">
                        <span class="txt1">
                            Don’t have an account?
                        </span>
                        <a href="{% url 'users:signup' %}" class="txt2">SignUp</a>
                        
                    </li>
                </ul>
            
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

{% endblock %}

users/templates/users/logout.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% block title %}
  The Shoppee | Logout
{% endblock %}

{% block content %}

<div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-4 "></span>
            
            <p class="lead mb-5">Your are logged out!</p>
            <p><a href="{% url 'users:login'%}" class="btn btn-sm btn-primary">Click here to log in again.</a></p>
          </div>
        </div>
      </div>
    </div>
  
{% endblock %}

users/templates/users/myorders.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  The Shoppee | My orders
{% endblock %}

{% block content %}

  <div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12 mb-0"><a href="/">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">My Orders</strong></div>
      </div>
    </div>
  </div>


  <div class="site-section">
      <div class="container">
            <h3 class="display-5 text-black mb-3 text-center">Purchase History</h3>
        <div class="row mb-5 justify-content-center">
        
            <div class="site-blocks-table">
              <table class="table table-bordered" >
                <thead>
                  <tr>
                  
                    <th class="product-name">Product</th>
                    <th class="product-price">Price</th>
                    <th class="product-quantity">Quantity</th>
                    
                  </tr>
                </thead>
                <tbody>
                {% for j in user_order %}
                    {% if j.user == user %}
                      {%  for i in item_order %}
                      <tr>
                          {% if i.order_id == j.id %}   
                          <td class="product-name">
                            <h2 class="h5 text-black">{{ i.product }}</h2>
                          </td>
                          <td>Rs. {{ i.price }}</td>
                          <td>{{ i.quantity }}</td>
                          {% endif %}
                        </tr>
                      {% endfor %}
                    {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>

          
        </div>
    </div>
      
  
{% endblock %}

users/templates/users/password_change.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
  The Shoppee | Change Password
{% endblock %}

{% block content %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-15 p-b-20">
            <form class="login100-form validate-form" method="POST">
                {{form.non_field_errors}}
                {% csrf_token %}
                <span class="login100-form-title p-b-45">
                    Change Password
                </span>
                {% for field in form%}
                <div class="wrap-input100 validate-input m-t-35 m-b-35" >                    
                    {% render_field field class="input100" %}
                    <span class="focus-input100" data-placeholder="{{ field.label }}"></span>
                </div>
                {% if field.errors %}
                <span class="txt2 login-more p-t-1 ">
                    {{ field.errors }}
                </span>
                {% endif %}
                {% endfor %}


                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        Change Password
                    </button>
                </div>
            </form>
            
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

{% endblock %}

users/templates/users/password_changed.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% block title %}
  The Shoppee | Logout
{% endblock %}

{% block content %}

<div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-4 "></span>
            
            <p class="lead mb-5">Password Changed!</p>
            
          </div>
        </div>
      </div>
    </div>
  
{% endblock %}

users/templates/users/signup.html
{% extends "shop/base.html" %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
  The Shoppee | SignUp
{% endblock %}

{% block content %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-15 p-b-20">
            <form class="login100-form validate-form" method="POST">
                {% csrf_token %}
                <span class="login100-form-title p-b-35">
                    SignUp
                </span>
                {% for field in form %}
                <div class="wrap-input100 validate-input m-t-35 m-b-35" data-validate = "Enter {{ field.label }}">
                    {% render_field field class="input100 has-val" %}
                    <span class="focus-input100" data-placeholder="{{ field.label }}"></span>
                </div>
                {% if field.errors %}
                <span class="txt2 login-more p-t-1 ">
                    {{ field.errors }}
                </span>
                {% endif %} 
                {% endfor %}
                <div class="container-login100-form-btn">
                    <button class="login100-form-btn" type="submit">
                        SignUp
                    </button>
                </div>
            </form>
            <ul class="login-more p-t-30">
                <li class="m-b-8">
                    <span class="txt1">
                        Already Registered?
                        <a href="{% url 'users:login' %}" class="txt2">Login</a>
                        
                    </span>
                    
                    
                </li>
            </ul>
        
          </div>
      </div>
</div>


{% endblock %}

users/templates/users/user_details.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  The Shoppee | Successfull
{% endblock %}

{% block content %}

<div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            
            <h2 class="display-5 text-black mb-3">Profile Details</h2>
            <span class="login100-form-avatar">
                    <img src="{% static "images/avatar-01.jpg" %}" alt="AVATAR">
            </span>
            <p class="lead mb-1 mt-4">Name: {{ user.first_name }} {{ user.last_name }}</p>
            <p class="lead mb-1">Address: {{ user.profile.address }}</p>
            <p class="lead mb-1">City: {{ user.profile.city }}</p>
            <p class="lead mb-1">PostCode: {{ user.profile.postcode }} </p>
            <p class="lead mb-3">DOB: {{ user.profile.date_birth }}</p>
            <p>
                
                        <form action="{% url 'users:change_password'%}">
                            <input type="submit" value="Change Password" class="btn btn-sm btn-primary"/>

                        </form>
            </p>
          </div>
        </div>
      </div>
    </div>
    
        
  
{% endblock %}