cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:    
    urlpatterns += static(settings.MEDIA_URL,                          
                            document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
            
app_name='shop'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

users/urls.py
"""Authenitcation URLs
"""

from django.conf.urls import url, include
from . import views
from . import views as core_views
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup_view, name='signup'),
    url(r'^details/$', views.detail_view, name='details'),
    url(r'^myorders/$', views.myorders, name='myorders'),
    url(r'^password/$', views.change_password, name='change_password'),

]

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200,
                            db_index=True)
    slug=models.SlugField(max_length=200,
                            unique=True)
    
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category=models.ForeignKey(Category,
                                related_name='products',
                                on_delete=models.CASCADE)
    name=models.CharField(max_length=200, db_index=True)
    slug=models.SlugField(max_length=200, unique=True)
    image=models.ImageField(upload_to='products/%Y/%m/%d', blank='True')
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    stock=models.IntegerField(default=0)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        index_together=(('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])
    

  

shop/forms.py
# sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    first_name=forms.CharField( max_length=50, required=False)
    last_name=forms.CharField( max_length=50, required=False)
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

shop/views.py
# sendemail/views.py
from django.contrib.auth.decorators import permission_required
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from .forms import ContactForm

from users.models import User
import datetime

def homepage(request):
    return render(request, 'shop/product/home.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


@login_required(login_url="/users/login")
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id,
                                         slug=slug,
                                         available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

def about(request): # new
        return render(request, 'shop/product/about.html')


def contact(request): # new
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            #first_name=form.cleaned_data['first_name']
            #last_name=form.cleaned_data['last_name']
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['sonishivam10@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/')
    return render(request, "shop/product/contact.html", {'form': form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}The Shoppee Store{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700"> 
    <link rel="stylesheet" href="{% static "fonts/icomoon/style.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/checkout.css" %}">
    <link rel="stylesheet" href="{% static "css/aos.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static "images/icons/favicon.ico" %}">
  <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
  <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
  <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}">
  <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %}">
  <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}">
  <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css" %}">
  <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css" %}">
  <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css" %}">
  <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main1.css" %}">
  <!--===============================================================================================-->

    
  </head>

  <body>
    
    <div class="site-wrap">
      <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
          <div class="container">
            <div class="row align-items-center">
  
              <!-----<div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                <form action="" class="site-block-top-search">
                  <span class="icon icon-search2"></span>
                  <input type="text" class="form-control border-0" placeholder="Search">
                </form>
              </div>-->
  
              <div class="col-auto mb-1 mb-md-0 col-md-4 order-1 order-md-2 text-left">
                <div class="site-logo">
                  <a href="/" class="js-logo-clone">The Shoppee</a>
                </div>
              </div>
  
              <div class="col-auto col-md-8 order-3 order-md-3 text-right">
                <div class="site-top-icons">
                  <ul >
                    {% if user.is_authenticated %}
                      <li >
                            <div class="dropdown">
                              <a href="#" role="button" class=" dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="icon icon-person"></span>
                              </a>
                              <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'users:details' %}">Hi {{ user.username }} </a>
                                <a class="dropdown-item" href="{% url 'users:myorders' %}">My Orders </a>
                                <form  action="{% url 'users:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="dropdown-item" href="{% url 'users:logout' %}" type="submit" >Logout</a>
                                </form>
                              </div>
                            </div>
                        </li>
                        <li>
                            {% with total_items=cart|length %}
                            <a href="{% url "cart:cart_detail" %}" class="site-cart">
                                <span class="icon icon-shopping_cart"></span>
                                <span class="count">
                                    {{ total_items}}
                            {% endwith %}
                            </span>
                          </a>
                        </li> 
                      
                    {% else %}
                      
                      <!--These dont need to be forms so need to be converted at some point
                          Also, they need to be added to the mobile collapsed menu-->
                          
                          <li >
                            <div class="dropdown">
                              <a href="#" role="button" class=" dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="icon icon-person"></span>
                              </a>
                              <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'users:login' %}">Login</a>
                                <a class="dropdown-item" href="{% url 'users:signup' %}">SignUp</a>
                              </div>
                            </div>
                          </li>
                          
                    {% endif %}
                   
                    
                    <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                  </ul>
                </div> 
              </div>
  
            </div>
          </div>
        </div> 
        <nav class="site-navigation text-right text-md-center" role="navigation">
          <div class="container">
            <ul class="site-menu js-clone-nav d-none d-md-block">
              <li>
                <a href="/">Home</a>
                
              </li>
              <li>
                <a href="{% url "shop:about" %}">About</a>
              </li>
              <li><a href="{% url "shop:product_list" %}">Shop</a></li>
              <!---<li><a href="#">Recommended</a></li>-->
              <li><a href="{% url "shop:contact" %}">Contact</a></li>
            </ul>
          </div>
        </nav>
      </header>


  
      
      <div >
          {% block content %}
          {% endblock %}
      </div>
    <footer class="site-footer border-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <div class="row">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigations</h3>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="/">Home</a></li>
                  <li><a href="{% url "shop:product_list" %}">Shop</a></li>
                  <li><a href="{% url "cart:cart_detail" %}">Shopping cart</a></li>
                  
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="{% url "shop:about" %}">About</a></li>
                  <li><a href="{% url "shop:contact" %}">Contact Us</a></li>
                 
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">Jaipur, Rajasthan</li>
                <li class="phone"><a href="tel://23923929210">+91-9001149471</a></li>
                <li class="email">sonishivama@gmail.com</li>
              </ul>
            </div>

           
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
            
            </p>
          </div>
          
        </div>
      </div>
    </footer>
  </div>
  
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
  <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "js/jquery-ui.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/checkout.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>
  <!--===============================================================================================-->
  <script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></script>
  <!--===============================================================================================-->
    <script src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
  <!--===============================================================================================-->
    <script src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
  <!--===============================================================================================-->
    <script src="{% static "vendor/select2/select2.min.js" %}"></script>
  <!--===============================================================================================-->
    <script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
    <script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
  <!--===============================================================================================-->
    <script src="{% static "vendor/countdowntime/countdowntime.js" %}"></script>
  <!--===============================================================================================-->
    <script src="{% static "js/main1.js" %}"></script>
    
  </body>
</html>